dist: xenial
language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$HOME/gopath/pkg/mod"
before_install:
- openssl aes-256-cbc -K $encrypted_e5acc89010f1_key -iv $encrypted_e5acc89010f1_iv -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- go get github.com/gohugoio/hugo
before_script:
- mkdir -p public_gitee 2> /dev/null
- mkdir -p public_github 2> /dev/null
script:
- hugo --baseURL https://jeremy-xu.oschina.io/ -d public_gitee
- hugo --baseURL https://jeremyxu2010.github.io/ -d public_github
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  email: "$GITHUB_EMAIL"
  name: "$GITHUB_USERNAME"
  github-url: github.com
  repo: jeremyxu2010/jeremyxu2010.github.io
  target_branch: master
  verbose: true
  keep-history: false
  local-dir: public_github
  on:
    branch: master
- provider: script
  script: bash .travis/deploy_to_gitee.sh
  on:
    branch: master
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com
